services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: book-shop
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  bsn-api:
    container_name: bsn-api
    image: lahirudilshan1/bsn-api:1.0.0
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - postgres

  bsn-ui:
    container_name: bsn-ui
    image: lahirudilshan1/bsn-ui:latest
    ports:
      - "8081:80"
    networks:
      - postgres
    depends_on:
      - bsn-api

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9098:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/book-shop
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: 1234

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"

#      KC_HTTP_ENABLED: true
      KC_HOSTNAME: 172.245.168.200
      KC_HOSTNAME_PORT: 9098
      KC_PROXY: edge

#      KC_HOSTNAME: 172.245.168.200
      KC_PROXY_HEADERS: xforwarded
    networks:
      - postgres
    command:
      - "start-dev"
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
  keycloak:
    driver: local
